### ISSUE TITLE
Pull to refresh padding ( for use with toolbar )

### ISSUE THREAD

**Issue by DavidPacioianu** [Yalantis/Phoenix#8]
There is no way to setProgressViewOffset(boolean scale, int start, int end) like for SwipeRefreshLayout.

**Comment by shliama** [comment]
Why don't you just align the listview below the toolbar?

**Comment by DavidPacioianu** [comment]
I can't do that because the toolbar is in the main layout and the recyclerView is used from a fragment. I use a padding for the recyclerView because I am hiding/showing it on scroll.

**Comment by shliama** [comment]
well, thanks to above merge request, I've come back here...
updated @DavidPacioianu method to be able to tweak all paddings and removed null-check, because in that place view cannot be null (it's initiated in the constructor).
You can use it like that:

```
mPullToRefreshView.setRefreshViewPadding(0, 100, 0, 0);
```

in this case, refresh view (the one with sun, sky etc.) will be offset by 100 pixels from top.
This is already available from maven repo, version 1.2.2
